# videomae_configs/kinetics_random_sth.yaml

# ===================================================================
#                       通用配置
# ===================================================================
# --- 基本信息 (来自 kinetics_finetune_sthv2.yaml) ---
dataset: sthv2
data_path: ../sthv2
ckpt_path: ./checkpoints
exp_name: videomaev2_random_finetune_sthv2 # 实验名: VideoMAE Random AL on STHV2
model_type: videomae
seed: 42

# --- 数据处理 & 模型配置 (来自 kinetics_finetune_sthv2.yaml) ---
train_batch_size: 16
val_batch_size: 4
workers: 12
clip_len: 16
# --- MMACTION2 配置 ---
model_cfg_path: ../mmaction2/configs/recognition/videomaev2/vit-base-p16_videomaev2-vit-g-dist-k710-pre_16x4x1_kinetics-400.py
model_ckpt_path: "../pretrained_checkpoints/vit-base-p16_videomaev2-vit-g-dist-k710-pre_16x4x1_kinetics-400_20230510-3e7f93b2.pth"
# --- 关键修改：确保类别数和特征维度正确 ---
num_classes: 20      # 注意：请根据你的STHV2子集的实际类别数修改此值
embed_dim: 768       # VideoMAEv2-Base 模型的特征维度是 768

# ===================================================================
#             主动学习 (Active Learning) 配置
# ===================================================================
al_algorithm: random        # <-- 关键: 指定AL算法为随机采样

initial_labeled_ratio: 0.05 # 初始标注比例：5%
budget_labels: 2000
num_each_iter: 20           # 每轮迭代新标注的样本数
# 注意: 由于总预算和每轮数量相等，主动学习只会运行一轮

# ===================================================================
#                       训练设置
# ===================================================================
optimizer:
  type: 'SGD'
  lr: 0.004
  weight_decay: 0.05

epoch_num: 35
patience: 10
al_train_epochs: 10   # 每次AL迭代后模型的再训练周期数

param_scheduler:
  - type: 'MultiStepLR'
    begin: 0
    end: 35
    by_epoch: True
    milestones: [10, 25]
    gamma: 0.1