# csn_configs/ig65m_finetune_ucf101.yaml (Corrected)

# 基本信息
dataset: ucf101
data_path: ../ucf101
ckpt_path: ./checkpoints
exp_name: ucf101_finetune_from_ig65m
model_type: csn

# 数据处理
train_batch_size: 8
val_batch_size: 4
workers: 8
clip_len: 32

# 训练设置
train: true
seed: 42
optimizer:
  type: 'SGD'
  lr: 0.000125
  momentum: 0.9
  weight_decay: 0.0001
epoch_num: 50
patience: 15

# 学习率调度器
param_scheduler:
  - type: 'MultiStepLR'
    begin: 0
    end: 50
    by_epoch: True
    milestones: [20, 40]
    gamma: 0.1

# MMACTION2 配置
# --- 核心修正：使用完整的模型配置文件，而不是 _base_ 文件 ---
model_cfg_path: ../mmaction2/configs/recognition/csn/ircsn_ig65m-pretrained-r152_8xb12-32x2x1-58e_kinetics400-rgb.py
model_ckpt_path: ../pretrained_checkpoints/ircsn_from_scratch_r152_ig65m_20200807-771c4135.pth
num_classes: 101      # UCF101的类别数
embed_dim: 2048

# 路径加载控制
checkpointer: false
test: false
final_test: false