# timesformer_configs/imagenet_entropy_ucf.yaml

# 基本信息
dataset: ucf101
data_path: ../ucf101
ckpt_path: ./checkpoints
exp_name: imagenet_entropy_ucf_exp # 实验名
model_type: timesformer
al_algorithm: entropy # <-- 核心：指定为熵采样

# 数据处理
train_batch_size: 8
val_batch_size: 4
workers: 8
clip_len: 8
num_each_iter: 20

# 路径加载控制
load_weights: false
load_opt: false
exp_name_toload: null
exp_name_toload_rl: null
snapshot: 0
checkpointer: true
test: false
final_test: false

# 训练设置
train: true
seed: 42
optimizer:
  type: 'SGD'
  lr: 0.0005
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True
epoch_num: 30
patience: 10
al_train_epochs: 5

# 学习率调度器
param_scheduler:
  - type: 'MultiStepLR'
    begin: 0
    end: 30
    by_epoch: True
    milestones: [15, 25]
    gamma: 0.1

# Active Learning 参数
initial_labeled_ratio: 0.05
budget_labels: 1000

# MMACTION2 配置
model_cfg_path: ../mmaction2/configs/recognition/timesformer/timesformer_spaceOnly_8xb8-8x32x1-15e_kinetics400-rgb.py
# --- 关键：使用在 ImageNet 上预训练的 ViT 权重 ---
model_ckpt_path: ../pretrained_checkpoints/vit_base_patch16_224.pth
num_classes: 101
embed_dim: 768